.TH XDL-COMPILER 1 "November 2006" "xdl-compiler"
.SH NAME
xdl-compiler \- Compiler for \fIlibxr\fR client server interfaces written in C.
.SH SYNOPSIS
.B xdl-compiler
[\fB-i\fR|\fB--install\fR]
[\fB-o\fR|\fB--upgrade\fR]
.CM ===========================================================================
.SH DESCRIPTION
\fBxdl-compiler\fR is compiler for \fIlibxr\fR client server interfaces written in C.
.CM ===========================================================================
.SH COMMAND LINE ARGUMENTS
.TP
\fB-i\fR, \fB--xdl\fR
Input XDL file.
.TP
\fB-o\fR, \fB--out\fR
Output directory.
.SH AUTHOR
Written by Ondrej Jirman, 2005-2006
.TP
Official website: http://oss.zonio.net
.SH BUGS
Bug reports can be sent to <oss@zonio.net>.
